### PR TITLE
Fix $hint and $orderby for the query recording

### LINKED ISSUE #31: The order of $hint and $orderby is not preserved
Since a JS object preserves order of the keys while Python and Go don't, we need to make sure that the keys in `$hint` and `$orderby` are in the right order.

Right now for example, an operation in the profile collection can look like this:
```
{
  "op": "query",
  "ns": "closeio.activity",
  "query": {
    "$query": {
      "organization": DBRef("organization", "orga_awqeiorqwejrlkqwerklqjwe"),
      "lead": DBRef("lead", "lead_asdlkjflaksjdflkajsdlfqiwueroiqu")
    },
    "$hint": {
      "lead": 1,
      "date_created": -1
    },
    "$orderby": {
      "date_created": -1
    }
  },
  ...
  "ntoreturn": 51,
  "ntoskip": 0,
}
```

... and is recorded as:

```
{"ns": "closeio.activity", "ts": {"$date": 1443222746092}, "ntoreturn": 51, "query": {"$hint": {"date_created": -1, "lead": 1}, "$orderby": {"date_created": -1}, "$query": {"organization": {"$ref": "organization", "$id": "orga_awqeiorqwejrlkqwerklqjwe"}, "lead": {"$ref": "lead", "$id": "lead_asdlkjflaksjdflkajsdlfqiwueroiqu"}}}, "ntoskip": 0, "op": "query"}
```

... and when you try to replay it, MongoDB returns:

```
2015-09-25T16:21:55.279-0700 I QUERY    [conn5792] assertion 17007 Unable to execute query: error processing query: ns=closeio.activity limit=51 skip=0
Tree: $and
    lead == { $ref: "lead", $id: "lead_asdlkjflaksjdflkajsdlfqiwueroiqu" }
    organization == { $ref: "organization", $id: "orga_awqeiorqwejrlkqwerklqjwe" }
Sort: { date_created: -1 }
Proj: {}
 planner returned error: bad hint ns:closeio.activity query:{ $hint: { date_created: -1, lead: 1 }, $orderby: { date_created: -1 }, $query: { organization: { $ref: "organization", $id: "orga_awqeiorqwejrlkqwerklqjwe" }, lead: { $ref: "lead", $id: "lead_asdlkjflaksjdflkajsdlfqiwueroiqu" } } }
```

### PR DESCRIPTION
**Pull request by wojcikstefan**
Fixes #31 (you can see the description of the problem under that issue)

### CODE REVIEW

**Comment by wojcikstefan** [comment]
Hi there @tredman! Are you by any chance the maintainer of this package? I still need to update/add some test cases in this PR, but wanted to get your feedback on it before I move forward.

**Comment by wojcikstefan** [comment]
@tmc I see you merged a PR in the latest commit to this repo. Are you still involved in its development? :)

**Comment by tredman** [comment]
Sorry for the delay on this!

This looks like it will work although it is a highly specific solution for just $hint and $orderBy and there are other cases where ordering is important and the tools break. This actually bit us at Parse when we were trying to use flashback with $centerSphere queries, where the order of fields matters, and we had to do some manual hacking of the output file to correct the order.

I think the lesson here is that JSON is a bad intermediate format for storage of ops between "record" and "replay" stages. To my knowledge there's no good way to marshall JSON in go and preserve order. We should write documents as raw BSON from the python tools and read them in as ordered BSON in go to avoid this.

Can't merge as there are conflicts, can you rebase and resolve? Thanks, Travis

**Comment by tredman** [comment]
Closing in favor of https://github.com/ParsePlatform/flashback/pull/35 which is a more thorough fix.

**Comment by wojcikstefan** [comment]
Thanks! Your solution looks *much* better!

**Pull request closed without merging**
