### PR TITLE
Multiple Oplogs, Dynamic Discover, Auth Support, Password Redaction for CLI output

### PR DESCRIPTION
**Pull request by dbmurphy**
Added 
    support for multiple OPLOG servers
Fixed
   PEP8  failures
   Tweaked oplog connection to use better flags for long running  collections

### CODE REVIEW

**Comment by dbmurphy** [comment]
Just realized  I am missing some redaction ( to not print passwords) I will get those added this afternoon US time.

**Comment by charity** [comment]
ok, let me know when ready to merge :)

**Comment by dbmurphy** [comment]
OK commits are in and just need a final set up tests  to make sure  this all work in the several cases that exists now


1) 1 Oplog, 1 Profiler
2) 1 Oplog, 1 Profiler with Auth
3) Multi Oplogs, Multi Profilers
4) Multi Oplogs, Multi Profilers with Auth
5) 1 Oplog, Multi Profilers with Auth
6) 1 Oplog, Multi Profilers 
7) Dynamic finding of just Primaries
8) Dynamic finding of just Primaries with Auth
9) Dynamic find of Primaries and Secondaries
10) Dynamic find of Primaries and Secondaries with Auth

Sorry these ended up being so connected merging the changes became more needed. Ill update this when I have test reports from each run ( this weekend hopefully)

**Comment by dbmurphy** [comment]
Tests Status:
Last updated  5/1/15 12:00 GMT

1) TODO
2) DONE **SUCCESS**
3) TODO
4) DONE **SUCCESS**
5) DONE **SUCCESS**
6) TODO
7) TODO
8) DONE **SUCCESS**
9) TODO
10) DONE **SUCCESS**

**Pull request merged**
